### ISSUE TITLE
Curious -- what was the ToS change?

### ISSUE THREAD

**Issue by gabrielgrant** [joeyh/git-annex#1]

**Comment by joeyh** [comment]
Please submit changes to http://git-annex.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. Just open a todo item there and link to a git repository containing your changes. Did you know, git is a distributed system? The git repository doesn't even need to be on github! Please send any complaints to Github; they don't allow turning off pull requests or redirecting them elsewhere.  -- A robot acting on behalf of Joey Hess
